Проект ShareIt. Add controllers
QuickHamster/ShareIt pull request #1
Opened 2022-08-18 07:27 UTC by QuickHamster

2022-08-18 16:33 UTC, kukolev requested changes

2022-08-18 16:33 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> + * // TODO . Будет реализовано в последующих спринтах
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-18 16:33 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> + * // TODO .
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-18 16:33 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> + * // TODO . Будет реализовано в последующих спринтах
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-18 16:33 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/exception/ValidationException.java
> +    public ValidationException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-18 20:47 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/user/exception/ValidationException.java
> +    public ValidationException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
ровно 120

2022-08-19 05:59 UTC, kukolev approved these changes

2022-08-19 06:33 UTC, merged