add-items-request
QuickHamster/ShareIt pull request #3
Opened 2022-10-24 22:46 UTC by QuickHamster

2022-10-27 11:52 UTC, kukolev requested changes

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInputDto.java
> +//@Data // Аннотация  добавит геттеры и сеттеры, а также методы toString(), equals(User other) и hashCode()
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public void validationPageable(int from, int size) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public void validationPageable(int from, int size) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    /*@PutMapping
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    /*@ManyToOne(fetch = FetchType.LAZY)
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestAnswerDto.java
> +    //@NotBlank(message = "Description cannot be blank")
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestAnswerDto.java
> +    //@FutureOrPresent(message = "Date cannot be in the past.")
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestAnswerDto.java
> +    //private Set<ItemDto> items;
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    //@FutureOrPresent(message = "Date cannot be in the past.")
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        bookingOutputDto = new BookingOutputDto(1L, LocalDateTime.now().plusDays(1), LocalDateTime.now().plusDays(2), null, null, BookingStatus.WAITING);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.start", startsWith(bookingOutputDto.getStart().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"))), String.class))
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.end", startsWith(bookingOutputDto.getEnd().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"))), String.class));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingDtoTest.java
> +        BookingOutputDto bookingOutputDto = new BookingOutputDto(1L, LocalDateTime.now().plusDays(1), LocalDateTime.now().plusDays(2), null, null, BookingStatus.WAITING);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        assertNotNull(bookingList);
Смысла теста с такой проверкой почти нет, т.к. тест не проверяет корректность выгрузки. Этот и подобные тесты нужно доработать - проверить, точно ли приложение работает так, как требуется.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    BookingService bookingService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-27 11:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    UserRepository userRepository;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-10-27 18:14 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInputDto.java
> +//@Data // Аннотация  добавит геттеры и сеттеры, а также методы toString(), equals(User other) и hashCode()
+

2022-10-27 18:14 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public void validationPageable(int from, int size) {
+

2022-10-27 18:14 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public void validationPageable(int from, int size) {
++

2022-10-27 18:15 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    /*@PutMapping
++

2022-10-27 18:18 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    /*@ManyToOne(fetch = FetchType.LAZY)
++

2022-10-27 18:19 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestAnswerDto.java
> +    //@NotBlank(message = "Description cannot be blank")
++

2022-10-27 18:19 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestAnswerDto.java
> +    //@FutureOrPresent(message = "Date cannot be in the past.")
++

2022-10-27 18:19 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestAnswerDto.java
> +    //private Set<ItemDto> items;
++

2022-10-27 18:20 UTC, QuickHamster commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    //@FutureOrPresent(message = "Date cannot be in the past.")
++

2022-10-27 18:21 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        bookingOutputDto = new BookingOutputDto(1L, LocalDateTime.now().plusDays(1), LocalDateTime.now().plusDays(2), null, null, BookingStatus.WAITING);
++

2022-10-27 18:22 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.start", startsWith(bookingOutputDto.getStart().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"))), String.class))
++

2022-10-27 18:22 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.end", startsWith(bookingOutputDto.getEnd().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"))), String.class));
++

2022-10-27 18:24 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/booking/BookingDtoTest.java
> +        BookingOutputDto bookingOutputDto = new BookingOutputDto(1L, LocalDateTime.now().plusDays(1), LocalDateTime.now().plusDays(2), null, null, BookingStatus.WAITING);
++

2022-10-27 18:25 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        assertNotNull(bookingList);
++

2022-10-27 18:33 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    BookingService bookingService;
++

2022-10-27 18:34 UTC, QuickHamster commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    UserRepository userRepository;
++

2022-10-28 16:24 UTC, kukolev approved these changes

2022-10-28 22:00 UTC, merged